### ISSUE TITLE
No entities from discovergy

### ISSUE THREAD

**Issue by samsmooth** [schlac/hacs-integration-discovergy#19]
Unfortunately there are no more entities from the plugin. Anyone having the same problem?

Might be related:
https://community.home-assistant.io/t/discovergy-power-meter/73142/30

**Comment by schlac** [comment]
@samsmooth Do you have any errors in the log? Pls also have a look at #16 and check if the problem persists with `v0.3.4`.

**Comment by samsmooth** [comment]
> @samsmooth Do you have any errors in the log? Pls also have a look at #16 and check if the problem persists with `v0.4.3`.

Thank you, upgrading via HACS resolved the problem.
