### ISSUE TITLE
Error setting up entry <EMAIL> for discovergy

### ISSUE THREAD

**Issue by filex99** [schlac/hacs-integration-discovergy#24]
Hi, 

the discovergy integration is not working any more. The Error Protocoll says: 

> Dieser Fehler wurde von einer benutzerdefinierten Integration verursacht
> 
> Logger: homeassistant.config_entries
> Source: custom_components/discovergy/__init__.py:74
> Integration: Discovergy
> First occurred: 09:47:27 (2 occurrences)
> Last logged: 09:58:04
> 
> Error setting up entry <EMAIL> for discovergy
> Traceback (most recent call last):
>   File "/usr/src/homeassistant/homeassistant/config_entries.py", line 387, in async_setup
>     result = await component.async_setup_entry(hass, self)
>   File "/config/custom_components/discovergy/__init__.py", line 74, in async_setup_entry
>     """Unload a config entry."""
> AttributeError: 'ConfigEntries' object has no attribute 'async_setup_platforms'
> 

I am running on
Home Assistant 2023.5.3
Supervisor 2023.04.1
Operating System 10.1
Frontend 20230503.3 - latest

I just updated to the last version of the integration, but this did not help. 
Thanks for your support!

**Comment by schlac** [comment]
Hi, That log looks as if it was generated by v0.1.0 or so. At that time there was no config dialog. If you just always upgraded HA. Could you try to configure the integration again? There should be a button  for that on the Integratons Tile. There is only one setting not related to the login but worth a try.
If that does not work please try to remove and add the Integraton to enter the setup values again.

PS I just checked the logs, I am running with 2023.5.3 and Discovergy 0.4.4 without any problems.

**Comment by filex99** [comment]
I completely deleted the integration and reinstalled it (copy of the current sources in Custom Components). 
Unfortunately, this did not help. 
Today came the HA update to 2023.5.4 - now the integration is active again. The total* entities show values again. The others were disabled. I have now activated them:
![image](https://github.com/schlac/hacs-integration-discovergy/assets/4587246/0299919b-f36b-45cd-9030-43a0e7a1217e)

**Comment by filex99** [comment]
The integration is up and running now since 5 Days.
I could not figure out, what the problem was. The HA update to version 2023.5.4 fixed it.
